# Generated by Django 5.1.6 on 2025-02-26 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Alumno')),
                ('career', models.CharField(max_length=50, verbose_name='Carrera')),
                ('dayAppointment', models.DateTimeField(verbose_name='Dia/Hora Apartado')),
                ('phoneNumber', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
        ),
    ]
