# Generated by Django 5.1.6 on 2025-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['dayAppointment'], 'verbose_name': 'Calendario', 'verbose_name_plural': 'Apartados'},
        ),
        migrations.AddField(
            model_name='calendar',
            name='roomType',
            field=models.CharField(choices=[('GREEN', 'Green Room'), ('AUDIO', 'Audio Room')], default='GREEN', max_length=5, verbose_name='Tipo de Sala'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['roomType', 'dayAppointment'], name='calendar_ap_roomTyp_a1f91f_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('roomType', 'dayAppointment'), name='unique_room_day'),
        ),
    ]
